### ISSUE TITLE
UnicodeDecodeError on install?

### ISSUE THREAD

**Issue by awhillas** [mirumee/google-i18n-address#9]
Getting this when i try to use `pip` to install it:
```python
	Collecting google-i18n-address==1.0.7 (from -r lib/saleor/requirements.txt (line 34))
	  Using cached google-i18n-address-1.0.7.tar.gz
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):
	      File "<string>", line 1, in <module>
	      File "/private/var/folders/43/8npcfbtj5mb6xw_1rv4sxy7m0000gn/T/pip-build-4yw78p57/google-i18n-address/setup.py", line 58, in <module>
	        long_description=get_long_description(),
	      File "/private/var/folders/43/8npcfbtj5mb6xw_1rv4sxy7m0000gn/T/pip-build-4yw78p57/google-i18n-address/setup.py", line 50, in get_long_description
	        readme = readme_file.read()
	      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
	        return codecs.ascii_decode(input, self.errors)[0]
	    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2470: ordinal not in range(128)
```
I'm using Python 3.5.0

**Comment by dappiu** [comment]
This can't be reproduced on Linux, and unfortunately I don't have a MacOS X with homebrew installed (which seems your case, looking the path names), but I suggest you to try to upgrade your brew and Python, since right now the python3 formula installs the 3.5.1 version.

`brew update && brew upgrade python3`

**Comment by arthurmaciel** [comment]
This error is happening here. Debian 8, Python 3.4. The error is exactly as presented.
